<a href="https://colab.research.google.com/github/amperez-crypto/infraestructura/blob/main/clase_21_feb_infraestructura.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

ruta_archivo = "/content/compras_semana.csv"
datos = pd.read_csv(ruta_archivo)
datos["total"] = datos["precio"] * datos["cantidad"]


(datos.head(5))

        producto  precio  cantidad  categoria  total
0          Leche     1.5         2  alimentos    3.0
1   Pan integral     0.8         3  alimentos    2.4
2       Manzanas     2.0         5     frutas   10.0
3           Café     3.5         1    bebidas    3.5
4  Pollo pechuga     8.5         1  proteínas    8.5

In [ ]:
import pandas as pd

ruta_archivo = "/content/compras_semana.csv"
datos = pd.read_csv(ruta_archivo)
datos["total"] = datos["precio"] * datos["cantidad"]
datos["total"].sum()

np.float64(44.699999999999996)

In [ ]:
import pandas as pd

ruta_archivo = "/content/compras_semana.csv"
datos = pd.read_csv(ruta_archivo)
datos["total"] = datos["precio"] * datos["cantidad"]

#Suma columna total
suma_compra = datos['total'].sum()
print(f"Total de compra: {suma_compra}")

#Promedio
promedio_compra = datos['total'].mean()
print(f"Promedio de compra: {promedio_compra}")

#mediana compras
mediana_compra = datos['total'].median
print(f"mediana de compra: {mediana_compra}")

registro_conteo = datos['total'].value_counts()
print(registro_conteo)

datos.describe()

Total de compra: 44.699999999999996
Promedio de compra: 4.47
mediana de compra: <bound method Series.median of 0     3.0
1     2.4
2    10.0
3     3.5
4     8.5
5     2.4
6     3.6
7     5.0
8     2.5
9     3.8
Name: total, dtype: float64>
total
3.0     1
2.4     1
10.0    1
3.5     1
8.5     1
2.4     1
3.6     1
5.0     1
2.5     1
3.8     1
Name: count, dtype: int64

          precio   cantidad      total
count  10.000000  10.000000  10.000000
mean    2.970000   2.100000   4.470000
std     2.383298   1.449138   2.663769
min     0.800000   1.000000   2.400000
25%     1.275000   1.000000   2.625000
50%     2.250000   1.500000   3.550000
75%     3.725000   2.750000   4.700000
max     8.500000   5.000000  10.000000

In [ ]:
import pandas as pd
ruta_archivo = "/content/peliculas_favoritas.json"
datos=pd.read_json(ruta_archivo)
datos

                titulo   año  puntuacion  duracion_minutos           genero
0  El viaje de Chihiro  2001         8.9               125        Animación
1     La vida es bella  1997         8.6               116            Drama
2         Pulp Fiction  1994         8.5               154           Crimen
3               Matrix  1999         8.7               136  Ciencia ficción
4         Forrest Gump  1994         8.8               142            Drama
5            Inception  2010         8.8               148  Ciencia ficción

In [ ]:
datos.describe()

               año  puntuacion  duracion_minutos
count     6.000000    6.000000          6.000000
mean   1999.166667    8.716667        136.833333
std       5.980524    0.147196         14.288690
min    1994.000000    8.500000        116.000000
25%    1994.750000    8.625000        127.750000
50%    1998.000000    8.750000        139.000000
75%    2000.500000    8.800000        146.500000
max    2010.000000    8.900000        154.000000